--------------------------------------------------------
--  File creato - giovedì-giugno-19-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ANALITI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SICAMPIONA"."ANALITI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5961 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CAMPIONAMENTI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SICAMPIONA"."CAMPIONAMENTI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 501 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTENITORI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SICAMPIONA"."CONTENITORI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11061 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MISURE_IN_LOCO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SICAMPIONA"."MISURE_IN_LOCO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1481 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRELEVATORI_SELEZIONABILI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SICAMPIONA"."PRELEVATORI_SELEZIONABILI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1761 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRELEVATORI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SICAMPIONA"."PRELEVATORI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ANALITI
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."ANALITI" 
   (	"ID_ANALITA" NUMBER, 
	"ID_CAMPIONAMENTO" NUMBER, 
	"CODICE" VARCHAR2(20 BYTE), 
	"DESCRIZIONE" VARCHAR2(200 BYTE), 
	"METODO_CODICE" VARCHAR2(20 BYTE), 
	"METODO_DESCRIZIONE" VARCHAR2(200 BYTE), 
	"PACCHETTO_CODICE" VARCHAR2(20 BYTE), 
	"PACCHETTO_DESCRIZIONE" VARCHAR2(200 BYTE), 
	"RIMOSSO_DA_OPER" NUMBER(1,0) DEFAULT 0, 
	"AGGIUNTO_DA_OPER" NUMBER(1,0) DEFAULT 0, 
	"VALORE_LIMITE" VARCHAR2(200 BYTE), 
	"UNITA_MISURA" VARCHAR2(20 BYTE), 
	"ORDINAMENTO" NUMBER DEFAULT 0
   ) ;
--------------------------------------------------------
--  DDL for Table CAMPIONAMENTI
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."CAMPIONAMENTI" 
   (	"ID_CAMPIONAMENTO" NUMBER, 
	"ENTE_CODICE" VARCHAR2(20 BYTE), 
	"ENTE_DENOMINAZIONE" VARCHAR2(100 BYTE), 
	"MATRICE_CODICE" VARCHAR2(20 BYTE), 
	"ARGOMENTO_CODICE" VARCHAR2(20 BYTE), 
	"ARGOMENTO_DENOMINAZIONE" VARCHAR2(200 BYTE), 
	"CLIENTE_CODICE" VARCHAR2(20 BYTE), 
	"CLIENTE_DENOMINAZIONE" VARCHAR2(200 BYTE), 
	"CLIENTE_CODICE_FISCALE" VARCHAR2(20 BYTE), 
	"CLIENTE_PARTITA_IVA" VARCHAR2(20 BYTE), 
	"PUNTO_ARPAL_CODICE" VARCHAR2(20 BYTE), 
	"PUNTO_ARPAL_DENOMINAZIONE" VARCHAR2(200 BYTE), 
	"PUNTO_ARPAL_INDIRIZZO" VARCHAR2(200 BYTE), 
	"PUNTO_ARPAL_COMUNE_CODICE" VARCHAR2(20 BYTE), 
	"PUNTO_ARPAL_COMUNE_DENOMINAZ" VARCHAR2(100 BYTE), 
	"PUNTO_ARPAL_LATITUDINE" VARCHAR2(100 BYTE), 
	"PUNTO_ARPAL_LONGITUDINE" VARCHAR2(100 BYTE), 
	"PUNTO_OPER_CODICE" VARCHAR2(20 BYTE), 
	"PUNTO_OPER_DENOMINAZ" VARCHAR2(200 BYTE), 
	"PUNTO_OPER_INDIRIZZO" VARCHAR2(200 BYTE), 
	"PUNTO_OPER_COMUNE_CODICE" VARCHAR2(20 BYTE), 
	"PUNTO_OPER_COMUNE_DENOMINAZ" VARCHAR2(100 BYTE), 
	"PUNTO_OPER_LATITUDINE" VARCHAR2(100 BYTE), 
	"PUNTO_OPER_LONGITUDINE" VARCHAR2(100 BYTE), 
	"DESCRIZIONE_ATTIVITA" VARCHAR2(1000 BYTE), 
	"DATA_ORA_CREAZIONE" DATE, 
	"DATA_PRELIEVO" DATE, 
	"ORA_PRELIEVO" VARCHAR2(5 BYTE), 
	"DATA_ORA_CHIUSURA" DATE, 
	"ULTIMO_AGG_DATA_ORA" DATE, 
	"ULTIMO_AGG_OPER_CODICE" VARCHAR2(20 BYTE), 
	"ULTIMO_AGG_OPER_COGNOME" VARCHAR2(100 BYTE), 
	"ULTIMO_AGG_OPER_NOME" VARCHAR2(100 BYTE), 
	"SIGLA_VERBALE" VARCHAR2(100 BYTE), 
	"NOTA_ACCETTAZIONE" VARCHAR2(1000 BYTE), 
	"NUMERO_CAMPIONE" VARCHAR2(100 BYTE), 
	"MATRICE_DENOMINAZIONE" VARCHAR2(100 BYTE), 
	"NOTA_ACCETTAZIONE_DATA_ORA" DATE, 
	"NOTA_ACCETTAZIONE_OPER_CODICE" VARCHAR2(20 BYTE), 
	"NOTA_ACCETTAZIONE_OPER_COGNOME" VARCHAR2(100 BYTE), 
	"NOTA_ACCETTAZIONE_OPER_NOME" VARCHAR2(100 BYTE), 
	"SUFFISSO_CARTELLA" VARCHAR2(50 BYTE), 
	"ELIMINATO" NUMBER(1,0) DEFAULT 0, 
	"FILE_VERBALE" VARCHAR2(50 BYTE), 
	"FILE_RAPPORTO_DI_PROVA" VARCHAR2(50 BYTE), 
	"STATO_CAMPIONE" VARCHAR2(100 BYTE), 
	"CF_OPERATORE_CREAZIONE" VARCHAR2(20 BYTE), 
	"ULTIMO_AGG_OPER_CF" VARCHAR2(20 BYTE), 
	"CODICE_SEDE_ACCETTAZIONE" VARCHAR2(2 BYTE), 
	"DATA_APERTURA_CAMPIONE" DATE, 
	"ORA_APERTURA_CAMPIONE" VARCHAR2(5 BYTE), 
	"EMAIL_INVIO_VERBALE" VARCHAR2(100 BYTE), 
	"PEC_INVIO_VERBALE" VARCHAR2(100 BYTE), 
	"CAMPIONAMENTO_COLLEGATO" VARCHAR2(100 BYTE), 
	"TIPO_CAMPIONAMENTO" VARCHAR2(50 BYTE), 
	"STATO_EMAIL_INVIO_VERBALE" VARCHAR2(50 BYTE), 
	"FILE_VERBALE_FIRMATO" VARCHAR2(100 BYTE), 
	"CAMPIONE_BIANCO" VARCHAR2(1000 BYTE), 
	"TEMPERATURA_ACCETTAZIONE" VARCHAR2(20 BYTE), 
	"LUOGO_APERTURA_CAMPIONE" VARCHAR2(250 BYTE), 
	"NOTE" VARCHAR2(500 BYTE)
   ) ;

   COMMENT ON COLUMN "SICAMPIONA"."CAMPIONAMENTI"."CAMPIONAMENTO_COLLEGATO" IS 'SIGLA_VERBALE del campionamento collegato';
--------------------------------------------------------
--  DDL for Table CONTENITORI
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."CONTENITORI" 
   (	"ID_CONTENITORE" NUMBER, 
	"ID_ANALITA" NUMBER, 
	"TIPO" VARCHAR2(100 BYTE), 
	"QUANTITA" NUMBER(*,0)
   ) ;
--------------------------------------------------------
--  DDL for Table MISURE_IN_LOCO
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."MISURE_IN_LOCO" 
   (	"ID_MISURA" NUMBER, 
	"ID_CAMPIONAMENTO" NUMBER, 
	"CODICE" VARCHAR2(20 BYTE), 
	"DESCRIZIONE" VARCHAR2(200 BYTE), 
	"METODO_CODICE" VARCHAR2(20 BYTE), 
	"METODO_DESCRIZIONE" VARCHAR2(200 BYTE), 
	"VALORE" VARCHAR2(20 BYTE), 
	"ANNOTAZIONI_OPERATORE" VARCHAR2(1000 BYTE), 
	"UNITA_MISURA" VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table PRELEVATORI
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."PRELEVATORI" 
   (	"ID_PRELEVATORE" NUMBER, 
	"ID_CAMPIONAMENTO" NUMBER, 
	"CODICE" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(100 BYTE), 
	"NOME" VARCHAR2(100 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table PRELEVATORI_SELEZIONABILI
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" 
   (	"ID_PRELEVATORE" NUMBER, 
	"ID_CAMPIONAMENTO" NUMBER, 
	"CODICE" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(100 BYTE), 
	"NOME" VARCHAR2(100 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table TIPI_CAMPIONAMENTO
--------------------------------------------------------

  CREATE TABLE "SICAMPIONA"."TIPI_CAMPIONAMENTO" 
   (	"MATRICE_CODICE" VARCHAR2(20 BYTE), 
	"TIPO_CAMPIONAMENTO" VARCHAR2(50 BYTE), 
	"DESCRIZIONE" VARCHAR2(200 BYTE), 
	"NOTE" VARCHAR2(1000 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Index CAMPIONAMENTI_INDEX1
--------------------------------------------------------

  CREATE INDEX "SICAMPIONA"."CAMPIONAMENTI_INDEX1" ON "SICAMPIONA"."CAMPIONAMENTI" ("NUMERO_CAMPIONE") 
  ;
--------------------------------------------------------
--  DDL for Index PRELEVATORI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."PRELEVATORI_PK" ON "SICAMPIONA"."PRELEVATORI" ("ID_PRELEVATORE") 
  ;
--------------------------------------------------------
--  DDL for Index CONTENITORI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."CONTENITORI_PK" ON "SICAMPIONA"."CONTENITORI" ("ID_CONTENITORE") 
  ;
--------------------------------------------------------
--  DDL for Index PRELEVATORI_SELEZIONABILI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."PRELEVATORI_SELEZIONABILI_PK" ON "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" ("ID_PRELEVATORE") 
  ;
--------------------------------------------------------
--  DDL for Index ANALITI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."ANALITI_PK" ON "SICAMPIONA"."ANALITI" ("ID_ANALITA") 
  ;
--------------------------------------------------------
--  DDL for Index CAMPIONAMENTI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."CAMPIONAMENTI_PK" ON "SICAMPIONA"."CAMPIONAMENTI" ("ID_CAMPIONAMENTO") 
  ;
--------------------------------------------------------
--  DDL for Index MISURE_IN_LOCO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."MISURE_IN_LOCO_PK" ON "SICAMPIONA"."MISURE_IN_LOCO" ("ID_MISURA") 
  ;
--------------------------------------------------------
--  DDL for Index TIPI_CAMPIONAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SICAMPIONA"."TIPI_CAMPIONAMENTO_PK" ON "SICAMPIONA"."TIPI_CAMPIONAMENTO" ("MATRICE_CODICE", "TIPO_CAMPIONAMENTO") 
  ;
--------------------------------------------------------
--  DDL for Trigger ANALITI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SICAMPIONA"."ANALITI_TRG" 
BEFORE INSERT ON ANALITI 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID_ANALITA IS NULL THEN
      SELECT ANALITI_SEQ.NEXTVAL INTO :NEW.ID_ANALITA FROM SYS.DUAL;
    END IF;
END;



/
ALTER TRIGGER "SICAMPIONA"."ANALITI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CAMPIONAMENTI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SICAMPIONA"."CAMPIONAMENTI_TRG" 
BEFORE INSERT ON CAMPIONAMENTI 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID_CAMPIONAMENTO IS NULL THEN
      SELECT CAMPIONAMENTI_SEQ.NEXTVAL INTO :NEW.ID_CAMPIONAMENTO FROM SYS.DUAL;
    END IF;
END;



/
ALTER TRIGGER "SICAMPIONA"."CAMPIONAMENTI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CONTENITORI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SICAMPIONA"."CONTENITORI_TRG" 
BEFORE INSERT ON CONTENITORI 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID_CONTENITORE IS NULL THEN
      SELECT CONTENITORI_SEQ.NEXTVAL INTO :NEW.ID_CONTENITORE FROM SYS.DUAL;
    END IF;
END;



/
ALTER TRIGGER "SICAMPIONA"."CONTENITORI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MISURE_IN_LOCO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SICAMPIONA"."MISURE_IN_LOCO_TRG" 
BEFORE INSERT ON MISURE_IN_LOCO 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID_MISURA IS NULL THEN
      SELECT MISURE_IN_LOCO_SEQ.NEXTVAL INTO :NEW.ID_MISURA FROM SYS.DUAL;
    END IF;
END;



/
ALTER TRIGGER "SICAMPIONA"."MISURE_IN_LOCO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRELEVATORI_SELEZIONABILI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SICAMPIONA"."PRELEVATORI_SELEZIONABILI_TRG" 
BEFORE INSERT ON PRELEVATORI_SELEZIONABILI 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID_PRELEVATORE IS NULL THEN
      SELECT PRELEVATORI_SELEZIONABILI_SEQ.NEXTVAL INTO :NEW.ID_PRELEVATORE FROM SYS.DUAL;
    END IF;
END;

/
ALTER TRIGGER "SICAMPIONA"."PRELEVATORI_SELEZIONABILI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRELEVATORI_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SICAMPIONA"."PRELEVATORI_TRG" 
BEFORE INSERT ON PRELEVATORI 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID_PRELEVATORE IS NULL THEN
      SELECT PRELEVATORI_SEQ.NEXTVAL INTO :NEW.ID_PRELEVATORE FROM SYS.DUAL;
    END IF;
END;



/
ALTER TRIGGER "SICAMPIONA"."PRELEVATORI_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ANALITI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."ANALITI" ADD CONSTRAINT "ANALITI_PK" PRIMARY KEY ("ID_ANALITA") ENABLE;
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("AGGIUNTO_DA_OPER" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("RIMOSSO_DA_OPER" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("PACCHETTO_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("METODO_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("ID_CAMPIONAMENTO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."ANALITI" MODIFY ("ID_ANALITA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRELEVATORI_SELEZIONABILI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" ADD CONSTRAINT "PRELEVATORI_SELEZIONABILI_PK" PRIMARY KEY ("ID_PRELEVATORE") ENABLE;
  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" MODIFY ("CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" MODIFY ("ID_CAMPIONAMENTO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" MODIFY ("ID_PRELEVATORE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRELEVATORI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."PRELEVATORI" ADD CONSTRAINT "PRELEVATORI_PK" PRIMARY KEY ("ID_PRELEVATORE") ENABLE;
  ALTER TABLE "SICAMPIONA"."PRELEVATORI" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI" MODIFY ("CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI" MODIFY ("ID_CAMPIONAMENTO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."PRELEVATORI" MODIFY ("ID_PRELEVATORE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPI_CAMPIONAMENTO
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."TIPI_CAMPIONAMENTO" ADD CONSTRAINT "TIPI_CAMPIONAMENTO_PK" PRIMARY KEY ("MATRICE_CODICE", "TIPO_CAMPIONAMENTO") ENABLE;
  ALTER TABLE "SICAMPIONA"."TIPI_CAMPIONAMENTO" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."TIPI_CAMPIONAMENTO" MODIFY ("TIPO_CAMPIONAMENTO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."TIPI_CAMPIONAMENTO" MODIFY ("MATRICE_CODICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTENITORI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."CONTENITORI" ADD CONSTRAINT "CONTENITORI_PK" PRIMARY KEY ("ID_CONTENITORE") ENABLE;
  ALTER TABLE "SICAMPIONA"."CONTENITORI" MODIFY ("QUANTITA" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CONTENITORI" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CONTENITORI" MODIFY ("ID_ANALITA" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CONTENITORI" MODIFY ("ID_CONTENITORE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAMPIONAMENTI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" ADD CONSTRAINT "CAMPIONAMENTI_PK" PRIMARY KEY ("ID_CAMPIONAMENTO") ENABLE;
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" ADD CONSTRAINT "CAMPIONAMENTI_CHK1" CHECK (STATO_EMAIL_INVIO_VERBALE IS NULL OR STATO_EMAIL_INVIO_VERBALE IN ('DA INVIARE','INVIATA','ERRORE')) ENABLE;
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("CODICE_SEDE_ACCETTAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ULTIMO_AGG_OPER_CF" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("CF_OPERATORE_CREAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ELIMINATO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("SUFFISSO_CARTELLA" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("MATRICE_DENOMINAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ULTIMO_AGG_OPER_NOME" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ULTIMO_AGG_OPER_COGNOME" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ULTIMO_AGG_OPER_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ULTIMO_AGG_DATA_ORA" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("DATA_PRELIEVO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("DATA_ORA_CREAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("CLIENTE_DENOMINAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("CLIENTE_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ARGOMENTO_DENOMINAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ARGOMENTO_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("MATRICE_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ENTE_DENOMINAZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ENTE_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."CAMPIONAMENTI" MODIFY ("ID_CAMPIONAMENTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MISURE_IN_LOCO
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" ADD CONSTRAINT "MISURE_IN_LOCO_PK" PRIMARY KEY ("ID_MISURA") ENABLE;
  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" MODIFY ("METODO_DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" MODIFY ("METODO_CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" MODIFY ("CODICE" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" MODIFY ("ID_CAMPIONAMENTO" NOT NULL ENABLE);
  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" MODIFY ("ID_MISURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ANALITI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."ANALITI" ADD CONSTRAINT "ANALITI_FK1" FOREIGN KEY ("ID_CAMPIONAMENTO")
	  REFERENCES "SICAMPIONA"."CAMPIONAMENTI" ("ID_CAMPIONAMENTO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTENITORI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."CONTENITORI" ADD CONSTRAINT "CONTENITORI_FK1" FOREIGN KEY ("ID_ANALITA")
	  REFERENCES "SICAMPIONA"."ANALITI" ("ID_ANALITA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MISURE_IN_LOCO
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."MISURE_IN_LOCO" ADD CONSTRAINT "MISURE_IN_LOCO_FK1" FOREIGN KEY ("ID_CAMPIONAMENTO")
	  REFERENCES "SICAMPIONA"."CAMPIONAMENTI" ("ID_CAMPIONAMENTO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRELEVATORI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."PRELEVATORI" ADD CONSTRAINT "PRELEVATORI_FK1" FOREIGN KEY ("ID_CAMPIONAMENTO")
	  REFERENCES "SICAMPIONA"."CAMPIONAMENTI" ("ID_CAMPIONAMENTO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRELEVATORI_SELEZIONABILI
--------------------------------------------------------

  ALTER TABLE "SICAMPIONA"."PRELEVATORI_SELEZIONABILI" ADD CONSTRAINT "PRELEVATORI_SELEZIONABILI_FK1" FOREIGN KEY ("ID_CAMPIONAMENTO")
	  REFERENCES "SICAMPIONA"."CAMPIONAMENTI" ("ID_CAMPIONAMENTO") ON DELETE CASCADE ENABLE;
